export type Member = {
  name: string;
  number: string;
  photo: string;
  /** Framing for the photo inside the card: CSS object-position and zoom. */
  photoPosition?: string;
  photoZoom?: number;
};

export type Stage = {
  number: number;
  title: string;
  /** What the report covers, shown next to the title. */
  topics?: string[];
  pages?: number;
  href: string;
  /** Cover + first inner page, generated by `npm run previews`. */
  previews?: [string, string];
  available: boolean;
};

export const navLinks = [
  { href: "#quem-somos", label: "Quem Somos" },
  { href: "#equipa", label: "Equipa" },
  { href: "#reports", label: "Reports" },
  { href: "#development", label: "Development" },
];

export const appHref = "./client/";

export const members: Member[] = [
  {
    name: "Dinis Santos",
    number: "72815",
    photo: "/members/Dinis.jpeg",
    photoZoom: 1.45,
    photoPosition: "50% 30%",
  },
  {
    name: "Guilherme Ribeiro",
    number: "75539",
    photo: "/members/Gui.jpeg",
    photoPosition: "50% 20%",
  },
  {
    name: "Joana Neves",
    number: "75205",
    photo: "/members/Joana.jpeg",
    photoPosition: "50% 25%",
  },
  {
    name: "Rodrigo Loução",
    number: "73984",
    photo: "/members/Loucao.jpeg",
    photoPosition: "45% 15%",
  },
];

const stageTopics: Record<number, { topics: string[]; pages: number }> = {
  1: { topics: ["Problema", "Utilizadores", "Objetivo"], pages: 2 },
  2: { topics: ["Utilizadores", "Tarefas"], pages: 3 },
};

export const stages: Stage[] = [1, 2, 3, 4, 5, 6].map((n) => {
  const info = stageTopics[n];
  return {
    number: n,
    title: `Stage ${n}`,
    href: `/reports/G_03_stage${n}.pdf`,
    available: Boolean(info),
    ...(info && {
      ...info,
      previews: [`/reports/previews/G_03_stage${n}-1.jpg`, `/reports/previews/G_03_stage${n}-2.jpg`],
    }),
  };
});
