export type Member = {
  name: string;
  number: string;
  photo: string;
  /** Framing for the photo inside the card: CSS object-position and zoom. */
  photoPosition?: string;
  photoZoom?: number;
};

export type Stage = {
  number: number;
  title: string;
  /** What the report covers, shown next to the title. */
  topics?: string[];
  pages?: number;
  href: string;
  /** Cover + first inner page, generated by `npm run previews`. */
  previews?: [string, string];
  available: boolean;
};

export type Side = "human" | "machine";

/** Split between the navbar's Pessoa (left) and Máquina (right) sides. */
export const navLinks: { id: string; label: string; side: Side }[] = [
  { id: "quem-somos", label: "Quem Somos", side: "human" },
  { id: "equipa", label: "Equipa", side: "human" },
  { id: "assignments", label: "Assignments", side: "human" },
  { id: "reports", label: "Reports", side: "machine" },
  { id: "development", label: "Development", side: "machine" },
];

export const appHref = "./client/";

export const members: Member[] = [
  {
    name: "Dinis Santos",
    number: "72815",
    photo: "/members/Dinis.jpeg",
  },
  {
    name: "Guilherme Ribeiro",
    number: "75539",
    photo: "/members/Gui.jpeg",
    photoPosition: "50% 20%",
  },
  {
    name: "Joana Neves",
    number: "75205",
    photo: "/members/Joana.jpeg",
    photoPosition: "50% 25%",
  },
  {
    name: "Rodrigo Loução",
    number: "73984",
    photo: "/members/Loucao.jpeg",
    photoPosition: "45% 15%",
  },
];

const stageTopics: Record<number, { topics: string[]; pages: number }> = {
  1: { topics: ["Problema", "Utilizadores", "Objetivo"], pages: 2 },
  2: { topics: ["Utilizadores", "Tarefas"], pages: 3 },
};

export const stages: Stage[] = [1, 2, 3, 4, 5, 6].map((n) => {
  const info = stageTopics[n];
  return {
    number: n,
    title: `Stage ${n}`,
    href: `/reports/G_03_stage${n}.pdf`,
    available: Boolean(info),
    ...(info && {
      ...info,
      previews: [`/reports/previews/G_03_stage${n}-1.jpg`, `/reports/previews/G_03_stage${n}-2.jpg`],
    }),
  };
});

export type Assignment = {
  number: number;
  title: string;
  /** Student numbers of the members who have submitted it. */
  submitted: string[];
};

/** Individual assignments. Add a student number to `submitted` once their PDF is in public/reports/. */
export const assignments: Assignment[] = [{ number: 1, title: "Assignment 1", submitted: ["75539"] }];

/** File naming convention: public/reports/assignment<N>-<student number>.pdf */
export const assignmentFile = (assignment: number, studentNumber: string) => ({
  href: `/reports/assignment${assignment}-${studentNumber}.pdf`,
  preview: `/reports/previews/assignment${assignment}-${studentNumber}-1.jpg`,
});
