const base = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;

export type Member = {
  name: string;
  number: string;
  photo: string;
  /** Framing for the photo inside the card: CSS object-position and zoom. */
  photoPosition?: string;
  photoZoom?: number;
};

export type Stage = {
  number: number;
  title: string;
  /** What the report covers, shown next to the title. */
  topics?: string[];
  pages?: number;
  href: string;
  /** Cover + first inner page, generated by `npm run previews`. */
  previews?: [string, string];
  available: boolean;
};

export type Side = "human" | "machine";

/** Split between the navbar's Pessoa (left) and Máquina (right) sides. */
export const navLinks: { id: string; label: string; side: Side }[] = [
  { id: "quem-somos", label: "Quem Somos", side: "human" },
  { id: "equipa", label: "Equipa", side: "human" },
  { id: "assignments", label: "Assignments", side: "human" },
  { id: "reports", label: "Reports", side: "machine" },
  { id: "logotipo", label: "Logótipo", side: "machine" },
  { id: "development", label: "Development", side: "machine" },
];

export const appHref = "./client/";

export const members: Member[] = [
  {
    name: "Dinis Santos",
    number: "72815",
    photo: base("/members/Dinis.jpeg"),
  },
  {
    name: "Guilherme Ribeiro",
    number: "75539",
    photo: base("/members/Gui.jpeg"),
    photoPosition: "50% 20%",
  },
  {
    name: "Joana Neves",
    number: "75205",
    photo: base("/members/Joana.jpeg"),
    photoPosition: "50% 25%",
  },
  {
    name: "Rodrigo Loução",
    number: "73984",
    photo: base("/members/Loucao.jpeg"),
    photoPosition: "45% 15%",
  },
];

const stageTopics: Record<number, { topics: string[]; pages: number }> = {
  1: { topics: ["Problema", "Utilizadores", "Objetivo"], pages: 2 },
  2: { topics: ["Utilizadores", "Tarefas"], pages: 3 },
};

export const stages: Stage[] = [1, 2, 3, 4, 5, 6].map((n) => {
  const info = stageTopics[n];
  return {
    number: n,
    title: `Stage ${n}`,
    href: base(`/reports/G_03_stage${n}.pdf`),
    available: Boolean(info),
    ...(info && {
      ...info,
      previews: [base(`/reports/previews/G_03_stage${n}-1.jpg`), base(`/reports/previews/G_03_stage${n}-2.jpg`)],
    }),
  };
});

export type Assignment = {
  number: number;
  title: string;
  /** Student numbers of the members who have submitted it. */
  submitted: string[];
};

/** Individual assignments. Add a student number to `submitted` once their PDF is in public/reports/. */
export const assignments: Assignment[] = [{ number: 1, title: "Assignment 1", submitted: ["75539"] }];

/** File naming convention: public/reports/assignment<N>-<student number>.pdf */
export const assignmentFile = (assignment: number, studentNumber: string) => ({
  href: base(`/reports/assignment${assignment}-${studentNumber}.pdf`),
  preview: base(`/reports/previews/assignment${assignment}-${studentNumber}-1.jpg`),
});

export type LogoVersion = {
  src: string;
  /** Short name for the step on the timeline. */
  name: string;
  title: string;
  description: string;
};

/** The logo from first sketch to final version, in order. Images live in public/logo/. */
export const logoVersions: LogoVersion[] = [
  {
    src: base("/logo/logo-v1.jpg"),
    name: "Trip Pack",
    title: "Uma mala a levantar voo",
    description:
      "O primeiro esboço, ainda com o nome Trip Pack: uma mala aberta de onde sai um avião. Junta as duas ideias de base da app, fazer a mala e viajar.",
  },
  {
    src: base("/logo/logo-v2.jpg"),
    name: "O rasto",
    title: "A checklist fica pelo caminho",
    description:
      "A mala desaparece e o avião passa a deixar um rasto de objetos e de vistos. Mostra a ideia central da app: a lista vai ficando feita à medida que se prepara a viagem.",
  },
  {
    src: base("/logo/logo-v3.jpg"),
    name: "Simplificar",
    title: "Menos detalhe, mais leitura",
    description:
      "Passado a limpo: ficam só o avião e três vistos. Com menos elementos, o logótipo continua legível mesmo em tamanho pequeno, como um ícone no telemóvel.",
  },
  {
    src: base("/logo/logo-v4.jpg"),
    name: "Pack&Sun",
    title: "Nasce o Pack&Sun",
    description:
      "A versão final, já com cor. O nome muda para Pack&Sun e o avião voa sobre um sol, ligando a mala ao tempo que vai fazer no destino.",
  },
];
